### ISSUE TITLE
Disable announcement does nothing

### ISSUE THREAD

**Issue by Luticus** [Fmstrat/ownnote#277]
App does not respect the "disable announcements" check box in the admin panel.  If I check this box then leave the admin panel and go back to it later the box well be reset to an unchecked state.  Announcements about the ownnote play store app are shown regardless of my wishes.

**Comment by mikebabb** [comment]
Possibly related to #287? ownNote settings in general not being saved?

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/ownnote/commit/1f0a01710326b15316d496397877038ba32ed417

**Comment by ejouvin** [comment]
Fix in 1f0a017 does not fix the case for disableAnnouncement.
A pull request #312  is done for that, there was an error in the parameter name in AJAX call.

Moreover, I had an issue after upgrade to OwnCloud 9.0.X ?
In the table oc_appconfig, the config value for the key "disableAnnouncement" was NULL.
In this case, I was not able to update the setting.

I had to change with a blank string in the database, and there everything works fine.
update oc_appconfig set configvalue='' where configkey='disableAnnouncement' and appid='ownnote';
